
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentLoginBtn = new javax.swing.JButton();
        caretakerLoginBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        studentRegistrationPanel = new javax.swing.JPanel();
        studentRegistrationPanel.setVisible(false);
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        registerStudentBtn = new javax.swing.JButton();
        studentUsernameEdit = new javax.swing.JTextField();
        studentEmailEdit = new javax.swing.JTextField();
        phoneEdit = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        studentPassEdit = new javax.swing.JPasswordField();
        confirmStudentPassEdit = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        loginBtn1 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        roomNoEdit = new javax.swing.JTextField();
        hostelNameEdit = new javax.swing.JComboBox<>();
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_information_tracker", "root", "");
            Statement statement = connection.createStatement();
            String hos = "SELECT * FROM hostels";
            ResultSet rs = statement.executeQuery(hos);
            while(rs.next()) {
                hostelNameEdit.addItem(rs.getString("Hostel"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        studentLoginPanel = new javax.swing.JPanel();
        studentLoginPanel.setVisible(false);
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usernameEdit = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        passEdit = new javax.swing.JPasswordField();
        errorView = new javax.swing.JLabel();
        errorView.setVisible(false);
        caretakerRegistrationPanel = new javax.swing.JPanel();
        caretakerRegistrationPanel.setVisible(false);
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        caretakerUsernameEdit = new javax.swing.JTextField();
        caretakerEmailEdit = new javax.swing.JTextField();
        caretakerPhoneEdit = new javax.swing.JTextField();
        caretakerPasswordEdit = new javax.swing.JPasswordField();
        caretakerConPassEdit = new javax.swing.JPasswordField();
        caretakerRegBtn = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        hostelEdit = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        noOfRoomsEdit = new javax.swing.JTextField();
        caretakerLoginPanel = new javax.swing.JPanel();
        caretakerLoginPanel.setVisible(false);
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        caretakerUsernameLogin = new javax.swing.JTextField();
        registerCaretakerBtn = new javax.swing.JButton();
        loginCaretakerBtn = new javax.swing.JButton();
        caretakerPasswordLogin = new javax.swing.JPasswordField();
        userProfilePanel = new javax.swing.JPanel();
        userProfilePanel.setVisible(false);
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        usernameView = new javax.swing.JTextField();
        emailView = new javax.swing.JTextField();
        hostelView = new javax.swing.JTextField();
        roomView = new javax.swing.JTextField();
        viewHostelsBtn = new javax.swing.JButton();
        availableHostelsPanel = new javax.swing.JPanel();
        availableHostelsPanel.setVisible(false);
        jLabel32 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableHostelsTable = new javax.swing.JTable();
        HIPanel = new javax.swing.JPanel();
        HIPanel.setVisible(false);
        hostelNameView = new javax.swing.JLabel();
        locationView = new javax.swing.JLabel();
        rentView = new javax.swing.JLabel();
        bookBtn = new javax.swing.JButton();
        caretakerProfilePanel = new javax.swing.JPanel();
        caretakerProfilePanel.setVisible(false);
        jLabel30 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        caretakerUsernameView = new javax.swing.JTextField();
        caretakerEmailView = new javax.swing.JTextField();
        caretakerHostelView = new javax.swing.JTextField();
        availableRoomsView = new javax.swing.JTextField();
        viewResidents = new javax.swing.JButton();
        residentsPanel = new javax.swing.JPanel();
        residentsPanel.setVisible(false);
        jScrollPane2 = new javax.swing.JScrollPane();
        residentsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LOGIN");

        studentLoginBtn.setText("STUDENT");
        studentLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentLoginBtnActionPerformed(evt);
            }
        });

        caretakerLoginBtn.setText("CARETAKER");
        caretakerLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caretakerLoginBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Welcome!! Kindly login to your respective portal. Create an account if you dont have one");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(studentLoginBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(caretakerLoginBtn)
                .addGap(70, 70, 70))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentLoginBtn)
                    .addComponent(caretakerLoginBtn))
                .addGap(821, 821, 821))
        );

        jLabel7.setText("Please fill in your details to register");

        jLabel8.setText("Username");

        jLabel9.setText("Email");

        jLabel10.setText("Phone  Number");

        jLabel11.setText("Gender");

        jLabel12.setText("Password");

        jLabel13.setText("Confirm Password");

        registerStudentBtn.setText("Register");
        registerStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerStudentBtnActionPerformed(evt);
            }
        });

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });

        jLabel14.setText("Already have an account?");

        loginBtn1.setText("Login");
        loginBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtn1ActionPerformed(evt);
            }
        });

        jLabel33.setText("Hostel");

        jLabel34.setText("Room Number");

        javax.swing.GroupLayout studentRegistrationPanelLayout = new javax.swing.GroupLayout(studentRegistrationPanel);
        studentRegistrationPanel.setLayout(studentRegistrationPanelLayout);
        studentRegistrationPanelLayout.setHorizontalGroup(
            studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentRegistrationPanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(registerStudentBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(studentRegistrationPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentRegistrationPanelLayout.createSequentialGroup()
                        .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentRegistrationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginBtn1))
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addGroup(studentRegistrationPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(studentRegistrationPanelLayout.createSequentialGroup()
                        .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(62, 62, 62)
                        .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderComboBox, 0, 231, Short.MAX_VALUE)
                            .addComponent(confirmStudentPassEdit)
                            .addComponent(studentUsernameEdit)
                            .addComponent(studentEmailEdit)
                            .addComponent(phoneEdit)
                            .addComponent(studentPassEdit)
                            .addComponent(roomNoEdit)
                            .addComponent(hostelNameEdit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        studentRegistrationPanelLayout.setVerticalGroup(
            studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentRegistrationPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addGap(24, 24, 24)
                .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(studentUsernameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(studentEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(phoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(hostelNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentRegistrationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentRegistrationPanelLayout.createSequentialGroup()
                        .addComponent(roomNoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(studentPassEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(confirmStudentPassEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registerStudentBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(studentRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(loginBtn1))
                .addContainerGap())
        );

        jLabel3.setText("Student Login");

        jLabel4.setText("Username");

        jLabel5.setText("Password");

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Don't have an account?");

        registerBtn.setText("Create one");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        errorView.setText("Incorrect Username or Password");

        javax.swing.GroupLayout studentLoginPanelLayout = new javax.swing.GroupLayout(studentLoginPanel);
        studentLoginPanel.setLayout(studentLoginPanelLayout);
        studentLoginPanelLayout.setHorizontalGroup(
            studentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentLoginPanelLayout.createSequentialGroup()
                .addGroup(studentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentLoginPanelLayout.createSequentialGroup()
                        .addContainerGap(70, Short.MAX_VALUE)
                        .addGroup(studentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(71, 71, 71)
                        .addGroup(studentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameEdit)
                            .addComponent(passEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentLoginPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(studentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(errorView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentLoginPanelLayout.createSequentialGroup()
                                .addGroup(studentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(loginBtn)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registerBtn))
                            .addGroup(studentLoginPanelLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel3)))))
                .addGap(95, 95, 95))
        );
        studentLoginPanelLayout.setVerticalGroup(
            studentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentLoginPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(studentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(usernameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(studentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(passEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginBtn)
                .addGap(18, 18, 18)
                .addGroup(studentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(registerBtn))
                .addGap(18, 18, 18)
                .addComponent(errorView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setText("Please fill in your details to register ");

        jLabel20.setText("Username");

        jLabel21.setText("Email");

        jLabel22.setText("Phone Number");

        jLabel23.setText("Password");

        jLabel24.setText("Confirm Password");

        caretakerRegBtn.setText("Register");
        caretakerRegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caretakerRegBtnActionPerformed(evt);
            }
        });

        jLabel31.setText("Hostel");

        jLabel39.setText("Number of Rooms");

        javax.swing.GroupLayout caretakerRegistrationPanelLayout = new javax.swing.GroupLayout(caretakerRegistrationPanel);
        caretakerRegistrationPanel.setLayout(caretakerRegistrationPanelLayout);
        caretakerRegistrationPanelLayout.setHorizontalGroup(
            caretakerRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, caretakerRegistrationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(caretakerRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, caretakerRegistrationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, caretakerRegistrationPanelLayout.createSequentialGroup()
                        .addComponent(caretakerRegBtn)
                        .addGap(153, 153, 153))))
            .addGroup(caretakerRegistrationPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(caretakerRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(caretakerRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caretakerEmailEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(caretakerUsernameEdit)
                    .addComponent(caretakerPhoneEdit)
                    .addComponent(caretakerPasswordEdit)
                    .addComponent(caretakerConPassEdit)
                    .addComponent(hostelEdit)
                    .addComponent(noOfRoomsEdit))
                .addContainerGap())
        );
        caretakerRegistrationPanelLayout.setVerticalGroup(
            caretakerRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caretakerRegistrationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(caretakerRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(caretakerUsernameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(caretakerRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(caretakerEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(caretakerRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(caretakerPhoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(caretakerRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(hostelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(caretakerRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(noOfRoomsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(caretakerRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caretakerPasswordEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(29, 29, 29)
                .addGroup(caretakerRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(caretakerConPassEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(caretakerRegBtn)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel15.setText("Caretaker Login");

        jLabel16.setText("Username");

        jLabel17.setText("Password");

        jLabel18.setText("Don't have an account? ");

        registerCaretakerBtn.setText("Create one");
        registerCaretakerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerCaretakerBtnActionPerformed(evt);
            }
        });

        loginCaretakerBtn.setText("Login");
        loginCaretakerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginCaretakerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout caretakerLoginPanelLayout = new javax.swing.GroupLayout(caretakerLoginPanel);
        caretakerLoginPanel.setLayout(caretakerLoginPanelLayout);
        caretakerLoginPanelLayout.setHorizontalGroup(
            caretakerLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caretakerLoginPanelLayout.createSequentialGroup()
                .addGroup(caretakerLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(caretakerLoginPanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel15))
                    .addGroup(caretakerLoginPanelLayout.createSequentialGroup()
                        .addGroup(caretakerLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(caretakerLoginPanelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(caretakerLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)))
                            .addGroup(caretakerLoginPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(caretakerLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caretakerUsernameLogin)
                            .addGroup(caretakerLoginPanelLayout.createSequentialGroup()
                                .addComponent(registerCaretakerBtn)
                                .addGap(0, 45, Short.MAX_VALUE))
                            .addComponent(caretakerPasswordLogin)))
                    .addGroup(caretakerLoginPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(loginCaretakerBtn)))
                .addContainerGap())
        );
        caretakerLoginPanelLayout.setVerticalGroup(
            caretakerLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caretakerLoginPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(caretakerLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(caretakerLoginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(caretakerLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(caretakerUsernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel17))
                    .addComponent(caretakerPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(loginCaretakerBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(caretakerLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(registerCaretakerBtn))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel25.setText("Student Profile");

        jLabel26.setText("Username");

        jLabel27.setText("Email");

        jLabel28.setText("Hostel");

        jLabel29.setText("Room Number");

        viewHostelsBtn.setText("View Hostels");
        viewHostelsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHostelsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userProfilePanelLayout = new javax.swing.GroupLayout(userProfilePanel);
        userProfilePanel.setLayout(userProfilePanelLayout);
        userProfilePanelLayout.setHorizontalGroup(
            userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userProfilePanelLayout.createSequentialGroup()
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userProfilePanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel29))
                        .addGap(51, 51, 51)
                        .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomView)
                            .addComponent(hostelView)
                            .addComponent(emailView)
                            .addComponent(usernameView)))
                    .addGroup(userProfilePanelLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel25)))
                .addContainerGap())
            .addGroup(userProfilePanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(viewHostelsBtn)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        userProfilePanelLayout.setVerticalGroup(
            userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(14, 14, 14)
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(usernameView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(emailView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(hostelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(userProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(roomView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(viewHostelsBtn)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel32.setText("Available Hostels");

        availableHostelsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Hostel", "Location", "Vacancies", "Rent", "Caretaker"
            }
        ));
        jScrollPane1.setViewportView(availableHostelsTable);

        javax.swing.GroupLayout availableHostelsPanelLayout = new javax.swing.GroupLayout(availableHostelsPanel);
        availableHostelsPanel.setLayout(availableHostelsPanelLayout);
        availableHostelsPanelLayout.setHorizontalGroup(
            availableHostelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availableHostelsPanelLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, availableHostelsPanelLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        availableHostelsPanelLayout.setVerticalGroup(
            availableHostelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availableHostelsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hostelNameView.setText("GREENS HOSTEL");

        locationView.setText("Greens");

        rentView.setText("RENT | 4500");

        bookBtn.setText("Click here to book");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HIPanelLayout = new javax.swing.GroupLayout(HIPanel);
        HIPanel.setLayout(HIPanelLayout);
        HIPanelLayout.setHorizontalGroup(
            HIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HIPanelLayout.createSequentialGroup()
                .addGroup(HIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HIPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(bookBtn))
                    .addGroup(HIPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(HIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationView)
                            .addComponent(hostelNameView)
                            .addComponent(rentView))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        HIPanelLayout.setVerticalGroup(
            HIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HIPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(hostelNameView)
                .addGap(26, 26, 26)
                .addComponent(locationView)
                .addGap(18, 18, 18)
                .addComponent(rentView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookBtn)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel30.setText("Caretaker Profile");

        jLabel35.setText("Username");

        jLabel36.setText("Email");

        jLabel37.setText("Hostel");

        jLabel38.setText("Available Rooms");

        viewResidents.setText("View Residents");
        viewResidents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewResidentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout caretakerProfilePanelLayout = new javax.swing.GroupLayout(caretakerProfilePanel);
        caretakerProfilePanel.setLayout(caretakerProfilePanelLayout);
        caretakerProfilePanelLayout.setHorizontalGroup(
            caretakerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caretakerProfilePanelLayout.createSequentialGroup()
                .addGroup(caretakerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(caretakerProfilePanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(caretakerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35)
                            .addComponent(jLabel38))
                        .addGap(51, 51, 51)
                        .addGroup(caretakerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(availableRoomsView)
                            .addComponent(caretakerHostelView)
                            .addComponent(caretakerEmailView)
                            .addComponent(caretakerUsernameView)))
                    .addGroup(caretakerProfilePanelLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel30)))
                .addContainerGap())
            .addGroup(caretakerProfilePanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(viewResidents)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        caretakerProfilePanelLayout.setVerticalGroup(
            caretakerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caretakerProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(14, 14, 14)
                .addGroup(caretakerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(caretakerUsernameView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(caretakerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(caretakerEmailView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(caretakerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(caretakerHostelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(caretakerProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(availableRoomsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(viewResidents)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        residentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Email", "Phone", "Gender", "Room Number"
            }
        ));
        jScrollPane2.setViewportView(residentsTable);

        javax.swing.GroupLayout residentsPanelLayout = new javax.swing.GroupLayout(residentsPanel);
        residentsPanel.setLayout(residentsPanelLayout);
        residentsPanelLayout.setHorizontalGroup(
            residentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        residentsPanelLayout.setVerticalGroup(
            residentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, residentsPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(caretakerLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(studentLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(caretakerProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(HIPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(133, 133, 133))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(caretakerRegistrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentRegistrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(residentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(availableHostelsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(studentLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(studentRegistrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(caretakerLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(caretakerRegistrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availableHostelsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HIPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(residentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addComponent(caretakerProfilePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentLoginBtnActionPerformed
        // TODO add your handling code here:
        loginPanel.setVisible(false);
        studentLoginPanel.setVisible(true);
    }//GEN-LAST:event_studentLoginBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        try {
            String username;
            username = usernameEdit.getText();
            String password = md5(new String(passEdit.getPassword()));
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_information_tracker", "root", "");
            Statement statement = connection.createStatement();
            String query = "SELECT * FROM students WHERE username = '"+username+"'";
            ResultSet resultSet = statement.executeQuery(query);

            while(resultSet.next()) {
                String dbPass = resultSet.getString("Password");
                if (password.equals(dbPass)) {
                    toDashBoard(username);
                } else {
                    errorView.setVisible(true);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        studentLoginPanel.setVisible(false);
        studentRegistrationPanel.setVisible(true);
    }//GEN-LAST:event_registerBtnActionPerformed

    private void registerStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerStudentBtnActionPerformed
        // TODO add your handling code here:
        String username, email, phone, gender, hostel, roomNo, password, confirmPassword;
        username = studentUsernameEdit.getText();
        email = studentEmailEdit.getText();
        phone = phoneEdit.getText();
        hostel = hostelNameEdit.getSelectedItem().toString();
        roomNo = roomNoEdit.getText();
        gender = genderComboBox.getSelectedItem().toString();
        password = md5(new String(studentPassEdit.getPassword()));
        confirmPassword = md5(new String(confirmStudentPassEdit.getPassword()));

        if(!validFields(username, email, phone, password, confirmPassword)) {
            System.out.println("Valid fields");
            sendToDatabase(username, email, phone, gender,hostel, roomNo, password);
        } else {
            System.out.println("Check fields and try again");
        }
    }//GEN-LAST:event_registerStudentBtnActionPerformed

    private void toDashBoard(String username) {
        studentLoginPanel.setVisible(false);
        userProfilePanel.setVisible(true);
        try {
            String password = md5(new String(passEdit.getPassword()));
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_information_tracker", "root", "");
            Statement statement = connection.createStatement();
            String query = "SELECT * FROM students WHERE username = '"+username+"'";
            ResultSet resultSet = statement.executeQuery(query);     

            while(resultSet.next()) {
                String email, hostel, roomNumber;
                email = resultSet.getString("Email");
                hostel = resultSet.getString("Hostel");
                roomNumber = resultSet.getString("Room Number");
                usernameView.setText(username);
                emailView.setText(email);
                hostelView.setText(hostel);
                roomView.setText(roomNumber);
            }

        } catch (SQLException ex) {
            Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public static String md5(String input) {
        try {
  
            // Static getInstance method is called with hashing MD5
            MessageDigest md = MessageDigest.getInstance("MD5");
  
            // digest() method is called to calculate message digest
            //  of an input digest() return array of byte
            byte[] messageDigest = md.digest(input.getBytes());
  
            // Convert byte array into signum representation
            BigInteger no = new BigInteger(1, messageDigest);
  
            // Convert message digest into hex value
            String hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        } 
  
        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
    
    private void sendToDatabase(String username, String email, String phone, String gender, String hostel, String roomNo, String password) {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_information_tracker", "root", "");
            try (Statement statement = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY)) {
                String checkIfStudntExists = "SELECT * FROM students WHERE Username = '"+username+"'";
                ResultSet rs = statement.executeQuery(checkIfStudntExists);
                if (rs != null) {
                    rs.last();
                    int count = rs.getRow();
                    if (count == 0) {
                        String query = "INSERT INTO students " + "VALUES (NULL, '"+username+"', '"+email+"', '"+phone+"', '"+gender+"', '"+password+"', '"+hostel+"', '"+roomNo+"')";
                        statement.executeUpdate(query);
                        statement.close();
                        studentRegistrationPanel.setVisible(false);
                        studentLoginPanel.setVisible(true);
                    } else {
                        System.out.println("The username is already in use " + count + " times.");
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentAccountCreation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean validFields(String username, String email, String phone, String password, String confirmPassword) {
        if (username.isEmpty()) {
            usernameEdit.requestFocus();
            return true;
        }
        
        if (email.isEmpty()) {
            studentEmailEdit.requestFocus();
            return true;
        }
         
        if (phone.isEmpty()) {
            phoneEdit.requestFocus();
            return true;
        }
        
        if (password.isEmpty()) {
            studentPassEdit.requestFocus();
            return true;
        }
        
        if (confirmPassword.isEmpty()) {
            confirmStudentPassEdit.requestFocus();
            return true;
        }
        
        if (!password.equals(confirmPassword)) {
            studentPassEdit.setBackground(Color.red);
            confirmStudentPassEdit.setBackground(Color.red);
            studentPassEdit.requestFocus();
            return true;
        }
        
        return false;
    }
    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void loginBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn1ActionPerformed
        // TODO add your handling code here:
        studentRegistrationPanel.setVisible(false);
        studentLoginPanel.setVisible(true);
    }//GEN-LAST:event_loginBtn1ActionPerformed

    private void caretakerLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caretakerLoginBtnActionPerformed
        // TODO add your handling code here:
        loginPanel.setVisible(false);
        caretakerLoginPanel.setVisible(true);
        
    }//GEN-LAST:event_caretakerLoginBtnActionPerformed

    private void registerCaretakerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerCaretakerBtnActionPerformed
        // TODO add your handling code here:
        caretakerLoginPanel.setVisible(false);
        caretakerRegistrationPanel.setVisible(true);
    }//GEN-LAST:event_registerCaretakerBtnActionPerformed

    private void caretakerRegBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caretakerRegBtnActionPerformed
        // TODO add your handling code here:
        String username, email, phone, hostel, noOfRooms, pass, conPass;
        username = caretakerUsernameEdit.getText();
        email = caretakerEmailEdit.getText();
        phone = caretakerPhoneEdit.getText();
        hostel = hostelEdit.getText();
        noOfRooms = noOfRoomsEdit.getText();
        pass = md5(new String(caretakerPasswordEdit.getPassword()));
        conPass = md5(new String(caretakerConPassEdit.getPassword()));
        
        if(!validFields(username, email, phone, hostel, noOfRooms, pass, conPass)){
            registerCaretaker(username, email, phone, hostel, noOfRooms, pass);
        }
    }//GEN-LAST:event_caretakerRegBtnActionPerformed

    private void viewHostelsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHostelsBtnActionPerformed
        // TODO add your handling code here:
        userProfilePanel.setVisible(false);
        availableHostelsPanel.setVisible(true);
        
        DefaultTableModel model = (DefaultTableModel) availableHostelsTable.getModel();
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_information_tracker", "root", "");
            Statement statement = connection.createStatement();
            String query = "SELECT * FROM hostels";
            ResultSet resultSet = statement.executeQuery(query);
            while(resultSet.next()) {
                String id, name, caretaker, location, vacancies, rent;
                id = resultSet.getString("ID");
                name = resultSet.getString("Hostel");
                vacancies = resultSet.getString("Vacancies");
                location = resultSet.getString("Location");
                caretaker = resultSet.getString("Caretaker");
                rent = resultSet.getString("Rent");
                model.addRow(new Object[] {id, name, location, vacancies, rent, caretaker});
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        availableHostelsTable.addMouseListener(new MouseListener(){
            @Override
            public void mouseClicked(MouseEvent e) {
                String id = model.getValueAt(availableHostelsTable.getSelectedRow(), 0).toString();
                availableHostelsPanel.setVisible(false);
                HIPanel.setVisible(true);
                try {
                    Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_information_tracker", "root", "");
                    Statement statement = connection.createStatement();
                    String query = "SELECT * FROM hostels WHERE ID = '"+id+"'";
                    ResultSet resultSet = statement.executeQuery(query);

                    while(resultSet.next()) {
                        String location, hostel, rent;
                        location = resultSet.getString("Location");
                        hostel = resultSet.getString("Hostel");
                        rent = resultSet.getString("Rent");
                        hostelNameView.setText(hostel);
                        locationView.setText(location);
                        rentView.setText(rent);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
       
    }//GEN-LAST:event_viewHostelsBtnActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        // TODO add your handling code here:
        JPanel panel = new JPanel();
        panel.setSize(new Dimension(250, 100));
        panel.setLayout(null);
        String hostel = hostelNameView.getText();
        String labl = new String("You are booking " + hostel +".");
        JLabel label1 = new JLabel(labl);
        label1.setVerticalAlignment(SwingConstants.BOTTOM);
        label1.setBounds(20, 20, 200, 30);
        label1.setHorizontalAlignment(SwingConstants.CENTER);
        panel.add(label1);
        JLabel label2 = new JLabel("Do you still want to proceed?");
        label2.setVerticalAlignment(SwingConstants.TOP);
        label2.setHorizontalAlignment(SwingConstants.CENTER);
        label2.setBounds(20, 80, 200, 20);
        panel.add(label2);
        UIManager.put("OptionPane.minimumSize", new Dimension(400, 200));
        int res = JOptionPane.showConfirmDialog(null, panel, "File",
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.PLAIN_MESSAGE);
        if(res == 0) {
           HIPanel.setVisible(false);
           userProfilePanel.setVisible(true);
        } else if (res == 1) {
           System.out.println("Pressed NO");
        } else {
           System.out.println("Pressed CANCEL");
        }
    }//GEN-LAST:event_bookBtnActionPerformed

    private void loginCaretakerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginCaretakerBtnActionPerformed
        // TODO add your handling code here:
        try {
            String username;
            username = caretakerUsernameLogin.getText();
            String password = md5(new String(caretakerPasswordLogin.getPassword()));
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_information_tracker", "root", "");
            Statement statement = connection.createStatement();
            String query = "SELECT * FROM caretakers WHERE username = '"+username+"'";
            ResultSet resultSet = statement.executeQuery(query);

            while(resultSet.next()) {
                String dbPass = resultSet.getString("Password");
                if (password.equals(dbPass)) {
                    toCaretakerDashBoard(username);
                } else {
                    errorView.setVisible(true);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginCaretakerBtnActionPerformed

    private void viewResidentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewResidentsActionPerformed
        // TODO add your handling code here:
        caretakerProfilePanel.setVisible(false);
        residentsPanel.setVisible(true);
        
        DefaultTableModel model = (DefaultTableModel) residentsTable.getModel();
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_information_tracker", "root", "");
            Statement statement = connection.createStatement();
            String caretaker = caretakerUsernameView.getText();
            String hostel;
            String getHostel = "SELECT * FROM caretakers WHERE Username = '"+caretaker+"'";
            ResultSet rs = statement.executeQuery(getHostel);
            while (rs.next()) {
                hostel = rs.getString("Hostel");
                String query = "SELECT * FROM students WHERE Hostel = '"+hostel+"'";
                ResultSet resultSet = statement.executeQuery(query);
                while(resultSet.next()) {
                    String id, username, email, phone, gender, roomNumber;
                    id = resultSet.getString("ID");
                    username = resultSet.getString("Username");
                    email = resultSet.getString("Email");
                    phone = resultSet.getString("Phone");
                    gender = resultSet.getString("Gender");
                    roomNumber = resultSet.getString("Room Number");
                    model.addRow(new Object[] {id, username, email, phone, gender, roomNumber});
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_viewResidentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HIPanel;
    private javax.swing.JPanel availableHostelsPanel;
    private javax.swing.JTable availableHostelsTable;
    private javax.swing.JTextField availableRoomsView;
    private javax.swing.JButton bookBtn;
    private javax.swing.JPasswordField caretakerConPassEdit;
    private javax.swing.JTextField caretakerEmailEdit;
    private javax.swing.JTextField caretakerEmailView;
    private javax.swing.JTextField caretakerHostelView;
    private javax.swing.JButton caretakerLoginBtn;
    private javax.swing.JPanel caretakerLoginPanel;
    private javax.swing.JPasswordField caretakerPasswordEdit;
    private javax.swing.JPasswordField caretakerPasswordLogin;
    private javax.swing.JTextField caretakerPhoneEdit;
    private javax.swing.JPanel caretakerProfilePanel;
    private javax.swing.JButton caretakerRegBtn;
    private javax.swing.JPanel caretakerRegistrationPanel;
    private javax.swing.JTextField caretakerUsernameEdit;
    private javax.swing.JTextField caretakerUsernameLogin;
    private javax.swing.JTextField caretakerUsernameView;
    private javax.swing.JPasswordField confirmStudentPassEdit;
    private javax.swing.JTextField emailView;
    private javax.swing.JLabel errorView;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JTextField hostelEdit;
    private javax.swing.JComboBox<String> hostelNameEdit;
    private javax.swing.JLabel hostelNameView;
    private javax.swing.JTextField hostelView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel locationView;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton loginBtn1;
    private javax.swing.JButton loginCaretakerBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JTextField noOfRoomsEdit;
    private javax.swing.JPasswordField passEdit;
    private javax.swing.JTextField phoneEdit;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton registerCaretakerBtn;
    private javax.swing.JButton registerStudentBtn;
    private javax.swing.JLabel rentView;
    private javax.swing.JPanel residentsPanel;
    private javax.swing.JTable residentsTable;
    private javax.swing.JTextField roomNoEdit;
    private javax.swing.JTextField roomView;
    private javax.swing.JTextField studentEmailEdit;
    private javax.swing.JButton studentLoginBtn;
    private javax.swing.JPanel studentLoginPanel;
    private javax.swing.JPasswordField studentPassEdit;
    private javax.swing.JPanel studentRegistrationPanel;
    private javax.swing.JTextField studentUsernameEdit;
    private javax.swing.JPanel userProfilePanel;
    private javax.swing.JTextField usernameEdit;
    private javax.swing.JTextField usernameView;
    private javax.swing.JButton viewHostelsBtn;
    private javax.swing.JButton viewResidents;
    // End of variables declaration//GEN-END:variables

    private void registerCaretaker(String username, String email, String phone, String hostel, String noOfRooms, String pass) {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_information_tracker", "root", "");
            try (Statement statement = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY)) {
                String checkIfCaretakerExists = "SELECT * FROM caretakers WHERE Username = '"+username+"'";
                ResultSet rs = statement.executeQuery(checkIfCaretakerExists);
                if (rs != null) {
                    rs.last();
                    int count = rs.getRow();
                    if (count == 0) {
                        String query = "INSERT INTO caretakers " + "VALUES (NULL, '"+username+"', '"+email+"', '"+phone+"', '"+pass+"', '"+hostel+"', '"+noOfRooms+"')";
                        statement.executeUpdate(query);
                        statement.close();
                        caretakerRegistrationPanel.setVisible(false);
                        caretakerLoginPanel.setVisible(true);
                    } else {
                        System.out.println("Records already exist. Please Confirm.");
                    }
                }
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentAccountCreation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean validFields(String username, String email, String phone, String hostel, String noOfRooms, String pass, String conPass) {
        if (username.isEmpty()) {
            caretakerUsernameEdit.requestFocus();
            return true;
        }
        
        if (email.isEmpty()) {
            caretakerEmailEdit.requestFocus();
            return true;
        }
         
        if (phone.isEmpty()) {
            caretakerPhoneEdit.requestFocus();
            return true;
        }
        
        if (hostel.isEmpty()) {
            hostelEdit.requestFocus();
            return true;
        }
        
        if (noOfRooms.isEmpty()) {
            noOfRoomsEdit.requestFocus();
            return true;
        }
        
        if (pass.isEmpty()) {
            caretakerPasswordEdit.requestFocus();
            return true;
        }
        
        if (conPass.isEmpty()) {
            caretakerConPassEdit.requestFocus();
            return true;
        }
        
        if (!pass.equals(conPass)) {
            caretakerPasswordEdit.setBackground(Color.red);
            caretakerConPassEdit.setBackground(Color.red);
            caretakerPasswordEdit.requestFocus();
            return true;
        }
        
        return false;
    }

    public String toCaretakerDashBoard(String username) {
        caretakerLoginPanel.setVisible(false);
        caretakerProfilePanel.setVisible(true);
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel_information_tracker", "root", "");
            Statement statement = connection.createStatement();
            String query = "SELECT * FROM caretakers WHERE username = '"+username+"'";
            ResultSet resultSet = statement.executeQuery(query);

            while(resultSet.next()) {
                String email, hostel, availableRooms;
                email = resultSet.getString("Email");
                hostel = resultSet.getString("Hostel");
                availableRooms = resultSet.getString("Available Rooms");
                caretakerUsernameView.setText(username);
                caretakerEmailView.setText(email);
                caretakerHostelView.setText(hostel);
                availableRoomsView.setText(availableRooms);
            }

        } catch (SQLException ex) {
            Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        return username;
    }
}
